### ISSUE TITLE
Minimum deployment target iOS 8.3

### ISSUE THREAD

**Issue by jersonperpetua** [Wolox/ReactiveArray#17]
First of all, awesome piece of code!

I checked and it seems like there is nothing specific to iOS 8.3 and up that this library needs. Can we lower the minimum deployment target to iOS 8.0 instead?

**Comment by guidomb** [comment]
I guess that should not be a problem. Can you send a PR?

**Comment by jersonperpetua** [comment]
Sure, no problem!
